import { LeadMobileItem } from './contact.interface';
import { EmailLeadDetails, FanpageLeadDetails, fieldExtensionChild, WebsiteLeadDetails } from './lead.interface';

export interface InterpriseModel {
  totalCount: number;
  items: InterpriseItem[];
}
export interface InterpriseItem {
  id: number;
  fullName?: null;
  mobile: string;
  email: string;
  website: string;
  cdmarketing?: null;
  utmcampaign?: null;
  utmsource?: null;
  industryClassification: string;
  customerGroup: string;
  source: string;
  classifyId?: null;
  productId?: null;
  sourceId: number;
  compnullAddress?: null;
  phone?: null;
  taxCode?: null;
  invoiceAddress?: null;
  fanpage: string;
  createdDate: Date;
  createdBy: number;
  updatedDate?: null;
  updatedBy?: null;
  brandName: string;
  leadId?: null;
  isDeleted: boolean;
  accountType?: null;
  note?: null;
  founding?: null;
  customerType?: null;
  tags: string;
  subdivision?: null;
  accountStatus?: null;
  representName?: null;
  utmmedium?: null;
  utmterm?: null;
  utmcontent?: null;
  createByName?: null;
  creatorEmail?: null;
  creationTime: Date;
  updateByName: string;
  modifierEmail: string;
  lastModificationTime: Date;
  ownerName: string;
  ownerId?: null;
  customerCode: string;
  globalCode: string;
  mobileFullText?: null;
  productBackup?: null;
  keyAccount: boolean;
  referId?: null;
  retailerId?: null;
  lastNote: string;
  dealValue?: number | null;
  contacts: [];
  contactName: string;
  lastActivities?: null;
  lastActivitiesTime?: null;
  abpOwnerEmail: string;
  abpOwnerId: string;

  //uncheck
  fieldExtensionChoice: fieldExtensionChild[] | null;
  fieldExtensionDate: fieldExtensionChild[] | null;
  fieldExtensionMultiSelect: fieldExtensionChild[] | null;
  fieldExtensionNumber: fieldExtensionChild[] | null;
  fieldExtensionText: fieldExtensionChild[] | null;
}

export interface CorporateDetailsModel {
  abpOwnerEmail: string;
  accountName: string | null;
  address: string | null;
  brandName: string;
  cdmarketing: string | null;
  classifyId: string | null;
  companyAddress: string | null;
  companyEmail: string | null;
  companyFanpage: string | null;
  companyInvoiceAddress: string | null;
  companyName: string | null;
  companyPhone: string | null;
  companyPipelineName: string | null;
  companyTaxCode: string | null;
  companyWebsite: string | null;
  contacts: ItemContactCorporate[];
  creationTime: string;
  creatorName: string;
  customerCode: string;
  customerGroup: string | null;
  customerGroupId: string | null;
  dateOfBirth: string | null;
  debt: number | string | null;
  debtLimit: number | string | null;
  deliveryLimit: number | string | null;
  department: string | null;
  emails: EmailLeadDetails[];
  expectationValue: number;
  facebook: string[] | null;
  fanpages: FanpageLeadDetails[] | null;
  fieldExtensionChoice: fieldExtensionChild[] | null;
  fieldExtensionDate: fieldExtensionChild[] | null;
  fieldExtensionMultiSelect: fieldExtensionChild[] | null;
  fieldExtensionNumber: fieldExtensionChild[] | null;
  fieldExtensionText: fieldExtensionChild[] | null;
  founding: string | null;
  fromSystem: string | null;
  fullName: string | null;
  hiddenInfo: boolean;
  homePhone: string | null;
  id: number;
  industryClassificationId: string | null | number;
  invoiceAddress: string | null;
  keyAccountPotentialProtectionEnabled: boolean;
  keyAccountProtectionEnabled: boolean;
  lastActivities: string | null | any;
  lastActivitiesTime: string | null;
  lastContactTime: string;
  lastModificationTime: string;
  latitude: string | number | null;
  leadCode: string | null | number;
  leadStatus: number;
  longtitude: number | string | null;
  mobiles: LeadMobileItem[] | null;
  modifierName: string;
  note: string | null;
  ownerName: string;
  placeId: string | null;
  position: number | string | null;
  representName: string | null;
  saleDictrict: string | null;
  saleGroup: string | null;
  saleOffice: string | null;
  saleOrg: string | null;
  shortName: string | null;
  sourceId: number;
  sourceName: string;
  subdivision: string;
  tags: string[] | null;
  taxCode: string | null;
  utmcampaign: string | null;
  utmcontent: string | null;
  utmmedium: string | null;
  utmsource: string | null;
  utmterm: string | null;
  websites: WebsiteLeadDetails[] | null;
}

export interface ItemContactCorporate {
  fullName: string;
  id: number;
}
