export enum AppRoutes {
  APP = 'App',
  AUTH = 'Auth',
  UNAUTH = 'UnAuth',

  // Tabbar
  DASHBOARD_TAB = 'DashboardTab',
  LEAD_TAB = 'LeadTab',
  CONTACT_TAB = 'ContactTab',
  ENTERPRISE_TAB = 'EnterpriseTab',
  DEAL_TAB = 'DealTab',
  // Screen
  LOGIN = 'Login',
  REGISTER = 'Register',
  LIST_LEAD = 'ListLead',
  LIST_CONTACT = 'ListContact',
  LIST_ENTERPRISE = 'ListEnterprise',
  LIST_DEAL = 'ListDeal',
  DETAIL_LEAD = 'DetailsLead',
  DETAIL_DEAL = 'DetailsDeal',
  DETAIL_CONTACT = 'DetailsContact',
  DETAIL_CORPORATE = 'DetailsCorporate',
  ADD_NOTE = 'AddNote',
  ADD_TASK = 'AddTask',
  ADD_APPOINTMENT = 'AddAppointment',
  PHONEBOOK = 'Phonebook',
  SEARCH_PHONE = 'SearchPhone',
  DETAIL_PHONEBOOK = 'DetailPhonebook',
  CREATE_PAYMENT_REQUEST = 'CreatePaymentRequest',
  PROFILE = 'Profile',
  DASHBOARD = 'Dashboard',
  DETAIL_MEETING = 'DetailMeeting',
  DATETIME = 'Datetime',
  COST = 'Cost',
  FILTER = 'Filter',
  SEARCH_LEAD = 'ListLeadSearch',
  SEARCH_USER_BY_ORGANIZATION = 'SearchUserByOrganization',
  CREATE_AND_EDIT_TASK = 'CreateAndEditTask',
  NOTIFICATION = 'Notification',
  CREATE_AND_EDIT_LEAD = 'CreateAndEditLead',
  CALL = 'Call',
  CREATE_AND_EDIT_APPOINTMENT = 'CreateAndEditAppointment',
  CREATE_AND_EDIT_LCCD = 'CreateAndEditLCCD',
  CONVERT_LEAD = 'ConvertLead',
  CALL_SCREEN = 'CallScreen',
}
